# Generated by Django 4.0.6 on 2022-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=2000)),
                ('faixa_salarial', models.TextField(max_length=20)),
                ('requisitos', models.TextField(max_length=100)),
            ],
        ),
    ]
