# Generated by Django 4.0.6 on 2022-07-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Vagas',
        ),
    ]
