# Generated by Django 4.0.6 on 2022-08-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_rename_livros_vagas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vagas',
            options={'verbose_name': 'Vaga'},
        ),
    ]
