# Generated by Django 4.0.6 on 2022-08-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_vagas_escolaridade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('destinado', models.CharField(max_length=100)),
            ],
        ),
    ]
