# Generated by Django 4.0.6 on 2022-08-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0006_vagas_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='destinado',
        ),
    ]
