# Generated by Django 4.0.6 on 2022-08-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0007_remove_categoria_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='faixa_salarial',
            field=models.IntegerField(max_length=3),
        ),
    ]
