# Generated by Django 4.0.6 on 2022-08-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0008_alter_vagas_faixa_salarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='faixa_salarial',
            field=models.TextField(max_length=3),
        ),
    ]
