# Generated by Django 4.1 on 2022-08-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0009_alter_vagas_faixa_salarial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='vagas',
            name='faixa_salarial',
            field=models.TextField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
