# Generated by Django 4.1 on 2022-08-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0012_vagas_candidatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='requisitos',
            field=models.TextField(max_length=2000),
        ),
    ]
