# Generated by Django 4.0.6 on 2022-08-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='Administrador',
        ),
    ]
