# Generated by Django 4.0.6 on 2022-08-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=64)),
                ('idade', models.CharField(max_length=4)),
            ],
        ),
    ]
