# Generated by Django 4.0.6 on 2022-08-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idade',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Pretencao_Salarial',
            field=models.CharField(choices=[('ate 1k', 'Ate 1k'), ('1k a 2k', '1k a 2k'), ('2k a 3k', '2k a 3K'), ('3k+', 'Acima de 3k')], max_length=10, null=True),
        ),
    ]
